apps/app/urls.py
from django.urls.conf import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

apps/users/urls.py
from re import template
from django.urls.conf import path, include
from . import views

app_name = 'users'

from django.views.generic import TemplateView

urlpatterns = [
    path('login/', TemplateView.as_view(template_name='users/login.html'), name='login'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('logout_user', views.logout_user, name='logout_user'),
]

boyFiestas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.app.urls')),
    path('', include('apps.users.urls')),
]

apps/app/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile


class UserForm(UserCreationForm):
	'''
	Formulario que utiliza el UserCreationForm incorporado para manejar la creación de usuarios.
	'''
	nombre = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Tu nombre..'}))
	apellidos = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Tus apellidos..'}))
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Correo electrónico..'}))
	password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Contraseña..','class':'password'}))
	password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Confirmar Contraseña..','class':'password'}))

	#reCAPTCHA token
	token = forms.CharField(
		widget=forms.HiddenInput())

	class Meta:
		model = User
		fields = ('username', 'nombre', 'apellidos', 'password1', 'password2', )


class AuthForm(AuthenticationForm):
	'''
	Formulario que utiliza el AuthenticationForm incorporado para gestionar la autentificación de los usuarios.
	'''
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Correo electrónico..'}))
	password = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Contraseña..','class':'password'}))

	class Meta:
		model = User
		fields = ('username','password', )


class UserProfileForm(forms.ModelForm):
	'''
	Modelo-forma básico para nuestro perfil de usuario que extiende el modelo de usuario de Django.
	'''
	direccion = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	ciudad = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	departamento = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	codigo_postal = forms.CharField(max_length=8, required=True, widget = forms.HiddenInput())
	pais = forms.CharField(max_length=40, required=True, widget = forms.HiddenInput())
	longitud = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())
	latitud = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())

	class Meta:
		model = UserProfile
		fields = ('direccion', 'ciudad', 'departamento', 'codigo_postal',
		 'pais', 'longitud', 'latitud')
         

app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

apps/app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'app/index.html')

apps/users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth

def login(request):
    return render(request, "users/login.html")
 
def sign_up(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        if User.objects.filter(username=username).exists():
            messages.warning(request, 'Nombre de usuario ya está en uso')
            return redirect('/login?st=sign-up')
        elif User.objects.filter(email=email).exists():
            messages.warning(request, 'Correo ya está en uso')
            return redirect('/login?st=sign-up')
        else:
            try:
                user = User.objects.create_user(username=username, password=password, email=email)
                user.save()
                messages.success(request, '¡Usuario creado con éxito!')
                return redirect('/')
            except:
                messages.warning(request, 'Ingresa datos válidos por favor')
                return redirect('/login?st=sign-up')
    else:
        return render(request, 'login.html')

def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, f'¡Bienvenido {user}!')
            return redirect('/')
        else:
            messages.warning(request, 'Nombre de usuario o contraseña inválido')
            return redirect('/login')
    else:
        return render(request, 'login.html')

def logout_user(request):
    auth.logout(request)
    messages.info(request, 'Has cerrado sesión')
    return redirect('/')

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth

def login(request):
    return render(request, "login.html")
 
def sign_up(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        if User.objects.filter(username=username).exists():
            messages.info(request, 'Nombre de usuario ya está en uso')
            return redirect('/login')
        elif User.objects.filter(email=email).exists():
            messages.info(request, 'Correo ya está en uso')
            return redirect('/login')
        else:
            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()
            return redirect('/')
    else:
        return render(request, 'login.html')

def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Nombre de usuario o contraseña inválido')
            return redirect('/login')
    else:
        return render(request, 'login.html')

def logout_user(request):
    auth.logout(request)
    return redirect('/')

app/templates/api/map.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}


{% endblock %}


{% block content %}

<h3 id="map">Django Google API Course - Map</h3>

<div class="container">

    <table>
        <thead>
            <tr>
                <th>Campo</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Comienzo</td>
                <td>{{directions.origin}}</td>
            </tr>
            <tr>
                <td>Destino</td>
                <td>{{directions.destination}}</td>
            </tr>
            <tr>
                <td>Duración</td>
                <td>{{directions.duration}}</td>
            </tr>
            <tr>
                <td>Distancia</td>
                <td>{{directions.distance}}</td>
            </tr>
            <tr>
                <td>Direcciones</td>
                <td id="dir-toggle">click <a href="javascript:void(0)" onclick="DirectionsToggle()">here</a></td>
            </tr>

        </tbody>
    </table>

    <table id="dir-table" hidden>
        <thead>
            <tr>
                <th>Direcciones</th>
                <th>Distancia</th>
                <th>Duración</th>
            </tr>
        </thead>
        <tbody>
            {% for leg in directions.route %}
            <tr>
                <td>Leg {{ forloop.counter }}</td>
                <td></td>
                <td></td>
            </tr>
            {% for dist, dur, text in leg.steps %}
            <tr>
                <td>{{text|safe}}</td>
                <td>{{dist}}</td>
                <td>{{dur}}</td>
            </tr>
            {% endfor %}
            {% endfor %}
        </tbody>
    </table>

</div>

<div class="map-container">

    <div id="map-route"></div>


</div>

{% endblock %}

{% block extend_footer %}

<!-- Faltaba comillas -->
<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";
    var lat_a = "{{lat_a|safe}}";
    var long_a = "{{long_a|safe}}";
    var lat_b = "{{lat_b|safe}}";
    var long_b = "{{long_b|safe}}";
    var lat_c = "{{lat_c|safe}}";
    var long_c = "{{long_c|safe}}";
    var lat_d = "{{lat_d|safe}}";
    var long_d = "{{long_d|safe}}";
    var origin = "{{origin|safe}}";
    var destination = "{{destination|safe}}";
    var directions = "{{directions|safe}}";

</script>

<script src="{% static 'assets/js/google_maps.js' %}"></script>


{% endblock %}

app/templates/api/route.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}


{% endblock %}


{% block content %}

<h3>Boy-Fiestas - Ruta</h3>

<div class="container">

    <label for="id-google-address-a">Dirección de partida</label>
    <input type="text" placeholder="*Comience a escribir la dirección" id="id-google-address-a" name="google_address_a">

    <label for="id-google-address-c">Punto de ruta 1</label>
    <input type="text" placeholder="*Comience a escribir la dirección" id="id-google-address-c" name="google_address_c">

    <label for="id-google-address-d">Punto de ruta 2</label>
    <input type="text" placeholder="*Comience a escribir la dirección" id="id-google-address-d" name="google_address_d">

    <label for="id-google-address-b">Dirección del destino</label>
    <input type="text" placeholder="*Comience a escribir la dirección" id="id-google-address-b" name="google_address_b">




    <input type="hidden" class="geo" id="id-lat-a" value="">
    <input type="hidden" class="geo" id="id-long-a" value="">
    <input type="hidden" class="geo" id="id-lat-b" value="">
    <input type="hidden" class="geo" id="id-long-b" value="">
    <input type="hidden" class="geo" id="id-lat-c" value="">
    <input type="hidden" class="geo" id="id-long-c" value="">
    <input type="hidden" class="geo" id="id-lat-d" value="">
    <input type="hidden" class="geo" id="id-long-d" value="">


</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";
    var base_country = "{{base_country|safe}}";

</script>

<script src="{% static 'assets/js/google_places_waypoints.js' %}"></script>


{% endblock %}

templates/app/index.html
{% extends 'app/layout.html' %}
{% block main %}
{% load static %}

<div class="tm-container">
    <div>
        <div class="tm-row pt-4">
            <div class="tm-col-left">
                <div class="tm-site-header media">
                    <i class="fas fa-umbrella-beach fa-3x mt-1 tm-logo"></i>
                    <div class="media-body">
                        <h1 class="tm-sitename text-uppercase">diagoona</h1>
                        <p class="tm-slogon">new bootstrap template</p>
                    </div>
                </div>
            </div>
            <div class="tm-col-right">
                <nav class="navbar navbar-expand-lg" id="tm-main-nav">
                    <button class="navbar-toggler toggler-example mr-0 ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbar-nav" aria-controls="navbar-nav" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span><i class="fas fa-bars"></i></span>
                    </button>
                    <div class="collapse navbar-collapse tm-nav" id="navbar-nav">
                        <ul class="navbar-nav text-uppercase">
                            <li class="nav-item active">
                                <a class="nav-link tm-nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link tm-nav-link" href="about.html">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link tm-nav-link" href="services.html">Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link tm-nav-link" href="contact.html">Contact</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        <div class="tm-row">
            <div class="tm-col-left"></div>
            <main class="tm-col-right">
                <section class="tm-content">
                    <h2 class="mb-5 tm-content-title">Diagoona HTML Template</h2>
                    <p class="mb-5">Diagoona is provided by TemplateMo website. You are allowed to use this template for
                        your websites. You are NOT allowed to redistribute this template ZIP file for a download purpose
                        on any template collection website.</p>
                    <hr class="mb-5">
                    <p class="mb-5">Diagoona is Bootstrap v4.4.1 layout. This BG is 50% transparent. You can set the
                        background images auto play settings (true or false in line number 33) in templatemo-script.js
                        file in js folder.</p>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Iniciar sesión</a>
                </section>
            </main>
        </div>
    </div>

    <div class="tm-row">
        <div class="tm-col-left text-center">
            <ul class="tm-bg-controls-wrapper">
                <li class="tm-bg-control active" data-id="0"></li>
                <li class="tm-bg-control" data-id="1"></li>
                <li class="tm-bg-control" data-id="2"></li>
            </ul>
        </div>
        <div class="tm-col-right tm-col-footer">
            <footer class="tm-site-footer text-right">
                <p class="mb-0">Copyright 2020 Diagoona Co.

                    | Design: <a rel="nofollow" target="_parent" href="https://templatemo.com"
                        class="tm-text-link">TemplateMo</a></p>
            </footer>
        </div>
    </div>

    <!-- Diagonal background design -->
    <div class="tm-bg">
        <div class="tm-bg-left"></div>
        <div class="tm-bg-right"></div>
    </div>
</div>
{% endblock %}

templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
{% include 'app/partial/head.html' %}

<body>

    <main>
        {% block main %}
        {% endblock %}
    </main>
    
    {% include 'app/partial/footer.html' %}
    {% include 'partial/alerts.html' %}

    <script src="{% static 'assets/js/app/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap_5/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/app/jquery.backstretch.min.js' %}"></script>
    <script src="{% static 'assets/js/app/templatemo-script.js' %}"></script>
    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
    
</body>

</html>

templates/app/partial/footer.html
{% load static %}
<footer>
  
</footer>

templates/app/partial/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Boy-Fiestas</title>
    <link href="{% static 'assets/css/alerts.css' %}" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet" /> <!-- https://fonts.google.com/ -->
    <link href="{% static 'vendor/bootstrap_5/css/bootstrap.min.css' %}" rel="stylesheet" /> <!-- https://getbootstrap.com/ -->
    <link href="{% static 'vendor/fontawesome/css/all.min.css' %}" rel="stylesheet" /> <!-- https://fontawesome.com/ -->
    <link href="{% static 'assets/css/app/templatemo-diagoona.css' %}" rel="stylesheet" />
</head>

templates/partial/alerts.html
{% load static %}
<div class="form-group">
    {% for message in messages %}
    <script src="{% static 'vendor/sweetalert/js/sweetalert.min.js' %}"></script>

    <script>
        swal({
            icon: '{{ message.tags }}',
            title: '{{ message }}',
            text: ' ',
            timer: 2350,
            buttons: false
        })
    </script>

    {% endfor %}

</div>

templates/users/login.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'assets/css/alerts.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/users/style.css' %}" />
  <title>Boyfiestas</title>
</head>

<body>

  <div class="container">
    <div class="forms-container">
      <div class="signin-signup">

        <form action="/sign_in" method="post" class="sign-in-form">
          {% csrf_token %}

          <h2 class="title">Iniciar sesion</h2>

          <div class="input-field">
            <i class="fas fa-user"></i>
            <input type="text" name="username" placeholder="Usuario" autocomplete="username" required/>
          </div>
          <div class="input-field">
            <i class="fas fa-lock"></i>
            <input type="password" name="password" placeholder="Contraseña" autocomplete="current-password" required/>
          </div>
          <input type="submit" value="Acceder" class="btn solid" />
          <p class="social-text">O inicia sesión con plataformas sociales</p>
          <div class="social-media">
            <a href="#" class="social-icon">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a arial-hidden="true" href="{% provider_login_url 'google' %}" class="social-icon">
              <i class="fab fa-google"></i>
            </a>
          </div>
          
        </form>
        <form action="/sign_up" method="post" class="sign-up-form">
          {% csrf_token %}

          <h2 class="title">Registrate</h2>

          <div class="input-field">
            <i class="fas fa-user"></i>
            <input type="text" name="username" placeholder="Nombre de usuario" autocomplete="username" required/>
          </div>
          <div class="input-field">
            <i class="fas fa-envelope"></i>
            <input type="email" name="email" placeholder="Correo" autocomplete="email" required/>
          </div>
          <div class="input-field">
            <i class="fas fa-lock"></i>
            <input type="password" name="password" placeholder="Contraseña" autocomplete="current-password" required/>
          </div>
          <input type="submit" class="btn" value="Acceder" />
          <p class="social-text">O regístrate con plataformas sociales</p>
          <div class="social-media">
            <a href="#" class="social-icon">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="{% provider_login_url 'google' %}" class="social-icon">
              <i class="fab fa-google"></i>
            </a>
          </div>
        </form>

      </div>
    </div>

    <div class="panels-container">
      <div class="panel left-panel">
        <div class="content">
          <h3>¿Nuevo aquí ?</h3>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis,
            ex ratione. Aliquid!
          </p>
          <button class="btn transparent" id="sign-up-btn">
            Registrate
          </button>
        </div>
        <img src="{% static 'assets/img/users/log.svg' %}" class="image" alt="" />
      </div>
      <div class="panel right-panel">
        <div class="content">
          <h3>¿Uno de nosotros ?</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
            laboriosam ad deleniti.
          </p>
          <button class="btn transparent" id="sign-in-btn">
            Iniciar sesion
          </button>
        </div>
        <img src="{% static 'assets/img/users/register.svg' %}" class="image" alt="" />
      </div>
    </div>
  </div>

  {% include 'partial/alerts.html' %}

  <script src="{% static 'assets/js/users/app.js' %}"></script>
  <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
</body>

</html>

users/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    </link>

    <!-- https://cdnjs.com/libraries/toastr.js/latest -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
        integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />


    <!-- Esto nos permite ampliar los scripts de cabecera en los documentos HTML que tienen requisitos especiales. -->


    {% block extend_head %}

    {% endblock %}

</head>

<body>

    <!-- Esto nos permite ampliar la barra de navegación en los documentos HTML que tienen requisitos especiales.-->
    {% include 'partials/nav.html' %}

    <div class="div-container">

        {% include 'partials/logo.html' %}

        {% block content %}

        {% endblock %}

    </div>

    <!--visit https://code.jquery.com/ for jquery script-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- https://cdnjs.com/libraries/toastr.js/latest -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
        integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Esto nos permite ampliar los scripts de pie en los documentos HTML que tienen requisitos especiales. -->
    {% block extend_footer %}

    {% endblock %}

    <script src="{% static 'assets/js/main.js' %}"></script>


</body>

</html>

users/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  <link rel="shortcut icon" href="{% static 'assets/img/icono.ico' %}">
  <title>Boyfiestas</title>
</head>

<body>

  <div class="container">
    <div class="forms-container">
      <div class="signin-signup">
        <form action="/sign_in" method="post" class="sign-in-form">
          {% csrf_token %}

          <div class="form-group">
            {% for message in messages %}
            <div style="color: red;">
              {{message}}
            </div>
            {% endfor %}
          </div>

          <h2 class="title">Iniciar sesion</h2>

          <div class="input-field">
            <i class="fas fa-user"></i>
            <input type="text" name="username" placeholder="Usuario" />
          </div>
          <div class="input-field">
            <i class="fas fa-lock"></i>
            <input type="password" name="password" placeholder="Contraseña" />
          </div>
          <input type="submit" value="Acceder" class="btn solid" />
          <p class="social-text">O inicia sesión con plataformas sociales</p>
          <div class="social-media">
            <a href="#" class="social-icon">
              <i class="fab fa-facebook-f"></i>
            </a>

            </a>
            <a href="#" class="social-icon">
              <i class="fab fa-google"></i>
            </a>


          </div>

        </form>
        <form action="/sign_up" method="post" class="sign-up-form">
          {% csrf_token %}

          <h2 class="title">Registrate</h2>
          <div class="input-field">
            <i class="fas fa-user"></i>
            <input type="text" name="username" placeholder="Nombre de usuario" />
          </div>
          <div class="input-field">
            <i class="fas fa-envelope"></i>
            <input type="email" name="email" placeholder="Correo" />
          </div>
          <div class="input-field">
            <i class="fas fa-lock"></i>
            <input type="password" name="password" placeholder="Contraseña" />
          </div>
          <input type="submit" class="btn" value="Acceder" />
          <p class="social-text">O regístrate con plataformas sociales</p>
          <div class="social-media">
            <a href="#" class="social-icon">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#" class="social-icon">
              <i class="fab fa-google"></i>
            </a>
          </div>
        </form>
      </div>
    </div>

    <div class="panels-container">
      <div class="panel left-panel">
        <div class="content">
          <h3>¿Nuevo aquí ?</h3>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis,
            ex ratione. Aliquid!
          </p>
          <button class="btn transparent" id="sign-up-btn">
            Registrate
          </button>
          <div style="margin-top: 5%; margin-left: 40%;">

            <a href="/" class="social-icon">
              <i class="fas fa-home"></i>
            </a>
          </div>
        </div>
        <img src="{% static 'assets/img/log.svg' %}" class="image" alt="" />
      </div>
      <div class="panel right-panel">
        <div class="content">
          <h3>¿Uno de nosotros ?</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
            laboriosam ad deleniti.
          </p>
          <button class="btn transparent" id="sign-in-btn">
            Iniciar sesion
          </button>
          <div style="margin-top: 5%; margin-left: 40%;">

            <a href="/" class="social-icon">
              <i class="fas fa-home"></i>
            </a>
          </div>
        </div>
        <img src="{% static 'assets/img/register.svg' %}" class="image" alt="" />
      </div>
    </div>



  </div>

  <script src="{% static 'assets/js/app.js' %}"></script>
</body>

</html>

users/templates/partials/logo.html
{% load static %}
<a href="{% url 'users:account' %}">
    <div class="brand-logo">
        <img class="logo" src="{% static 'branding/did_logo.gif' %}" />
    </div>
</a>

users/templates/partials/nav.html
{% if request.user.is_authenticated %}
<ul class="sidenav">
    {% if request.path == "/" %}
    <li><a class="active" href="{% url 'users:account' %}">Cuenta del Usuario</a></li>
    {% else %}
    <li><a href="{% url 'users:account' %}">Cuenta del Usuario</a></li>
    {% endif %}

    {% if "profile" in request.path %}
    <li><a class="active" href="{% url 'users:profile' %}">Perfil del Usuario</a></li>
    {% else %}
    <li><a href="{% url 'users:profile' %}">Perfil del Usuario</a></li>
    {% endif %}

    {% if "route" in request.path %}
    <li><a class="active" href="{% url 'app:route' %}">Ruta</a></li>
    {% else %}
    <li><a href="{% url 'app:route' %}">Ruta</a></li>
    {% endif %}

    {% if "map" in request.path %}
    <li><a class="active" href="{% url 'app:map' %}">Mapa</a></li>
    {% else %}
    <li><a href="{% url 'app:map' %}">Mapa</a></li>
    {% endif %}

    {% if "sign-out" in request.path %}
    <li><a class="active" href="{% url 'users:sign-out' %}">Cerrar sesión</a></li>
    {% else %}
    <li><a href="{% url 'users:sign-out' %}">Cerrar sesión</a></li>
    {% endif %}

</ul>
{% else %}
<ul class="sidenav">

    {% if "sign-in" in request.path %}
    <li><a class="active" href="{% url 'users:sign-in' %}">Iniciar sesión</a></li>
    {% else %}
    <li><a href="{% url 'users:sign-in' %}">Iniciar sesión</a></li>
    {% endif %}

    {% if "sign-up" in request.path %}
    <li><a class="active" href="{% url 'users:sign-up' %}">Registrarse</a></li>
    {% else %}
    <li><a href="{% url 'users:sign-up' %}">Registrarse</a></li>
    {% endif %}
</ul>
{% endif %}